# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/kapilgahtori989@gmail.com/first_pipeline-(1)")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM learning_spark_sql.dlt_pipeline.sample_aggregation_first_pipeline"))

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from learning_spark_sql.dlt_pipeline.business_sales;
